Analysis template implementation complete
1053-August-Duet-Project-Registry/project-registry-project-microservice pull request #2
Opened 2021-07-20 21:18 UTC by jpbulloch5

The project-microservice now successfully implements the analysis.yml template from the project-registry-devops repo.

2021-07-20 22:06 UTC, escalonn requested changes
cf. https://github.com/1053-August-Duet-Project-Registry/project-registry-account-microservice/pull/3#pullrequestreview-711097506

2021-07-21 05:03 UTC, escalonn requested changes
see https://github.com/1053-August-Duet-Project-Registry/project-registry-account-microservice/pull/3#pullrequestreview-711258014
also, the build is failing (and it should be a required check via branch policy).

2021-07-21 18:57 UTC, jpbulloch5 commented
updated grammar/spelling on comment block to match other pipelines

2021-07-21 21:40 UTC, escalonn approved these changes

2021-07-21 21:44 UTC, BeoHawk25 approved these changes

2021-07-21 22:25 UTC, merged